### ISSUE TITLE
i am getting this error what is problem, .  core.js:19866 ERROR TypeError: Lt.makeTensor is not a function

### ISSUE THREAD

**Issue by kansald006** [kamiazya/ngx-face-api-js#256]
**Describe the bug**

i am getting this error what is problem .

core.js:19866 ERROR TypeError: Lt.makeTensor is not a function

**Comment by kamiazya** [comment]
@kansald006 

Hi,

I think it is an error that occurs when the version of Angular or TypeScript does not match.
Or version of dependency package such as tenforflow.js is wrong.

This project has only been tested with Angular 7, so try Angular 7 in your project and try.

Thanks.
