### ISSUE TITLE
How can i use this for video tag to capture expression in real time

### ISSUE THREAD

**Issue by CodingDude-mkun** [kamiazya/ngx-face-api-js#383]
hello @kamiazya ,
i am trying to use this in ionic 4 and want to know how this can be used with <video> tag and how can i get the face expressions from webcam directly in real time

**Comment by kamiazya** [comment]
@CodingDude-mkun 

You can attach the directive provided by this library to the video tag.

This project may be helpful for you.

Good luck.

https://github.com/kamiazya/ngx-face-api-js-demo-webcam
